parameters:
    genderize_io_endpoint: "https://api.genderize.io/"

services:
    genderize_io.client:
        class: Jhg\GenderizeIoClient\HttpClient\GenderizeClient

    genderize_io.genderizer:
        class: Jhg\GenderizeIoClient\Genderizer\Genderizer
        arguments: [@genderize_io.client]

    genderizer:
        alias: genderize_io.genderizer

    genderize_io.twig:
        class: Jhg\GenderizeIoBundle\Twig\GenderizeExtension
        arguments: [@genderize_io.genderizer]
        tags:
            - { name: twig.extension }